-- Criar tabela
CREATE TABLE TBCONTATO (
    ID SERIAL PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100),
    TELEFONE VARCHAR(25),
    DATACRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DATAATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Inserir dados de exemplo para teste
INSERT INTO TBCONTATO (NOME, EMAIL, TELEFONE) VALUES ('Maria Silva', 'maria.silva@example.com', '123456789');
INSERT INTO TBCONTATO (NOME, EMAIL, TELEFONE) VALUES ('João Souza', 'joao.souza@example.com', '987654321');
INSERT INTO TBCONTATO (NOME, EMAIL, TELEFONE) VALUES ('Ana Pereira', 'ana.pereira@example.com', '555666777');
INSERT INTO TBCONTATO (NOME, EMAIL, TELEFONE) VALUES ('Carlos Mendes', 'carlos.mendes@example.com', '222333444');
INSERT INTO TBCONTATO (NOME, EMAIL, TELEFONE) VALUES ('Luiza Oliveira', 'luiza.oliveira@example.com', '999888777');
