CREATE TABLE TBCATEGORIAS(
       ID SERIAL PRIMARY KEY,
	   NOME VARCHAR(255) NOT NULL,
	   STATUS BOOLEAN DEFAULT TRUE
);

CREATE TABLE TBPOSTS(
        ID SERIAL PRIMARY KEY,
		TITULO VARCHAR(255) NOT NULL,
		CONTEUDO TEXT NOT NULL,
		CATEGORIA_ID INTEGER NOT NULL,
		DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
		STATUS BOOLEAN DEFAULT TRUE,
		FOREIGN KEY (CATEGORIA_ID) REFERENCES TBCATEGORIAS(ID) ON DELETE CASCADE
);

CREATE TABLE TBCOMENTARIOS(
       ID SERIAL PRIMARY KEY,
	   POST_ID INTEGER NOT NULL,
	   CONTEUDO TEXT NOT NULL,
	   DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	   STATUS BOOLEAN DEFAULT TRUE,
	   FOREIGN KEY (POST_ID) REFERENCES TBPOSTS(ID) ON DELETE CASCADE
);